name: AurionEconomy
version: ${version}
main: com.mineaurion.aurioneconomy.bukkit.Bootstrap
authors: [Yann151924]
website: https://mineaurion.com
depend:
  - Vault
commands:
  money:
    description: "Money Command"
    aliases:
      - economy
      - aurion
