name: Economy
version: ${version}
main: com.mineaurion.economy.bukkit.Bootstrap
authors: [Yann151924]
website: https://mineaurion.com
load: STARTUP
commands:
  money:
    description: "Money Command"
    aliases:
      - economy
      - aurion