name: Build
on:
  pull_request:
    branches: [ master ]

jobs:
  # Only build the source branch not specific branch for 1.16, 1.18 & 1.20
  # The build is only use for debugging purpose & get the artifact since there is no test in the code. Ultimately it test that the java can be compiled
  build:
    strategy:
      matrix:
        platform: [ "bukkit", "sponge", "forge", "fabric" ]
        branch: ["${{ github.event.pull_request.head.ref }}"]
    uses: ./.github/workflows/build.yaml
    with:
      platform: ${{ matrix.platform }}
      branch: ${{ matrix.branch }}